spring.application.name=OnlineBookStoreProject

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/online_book_store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Indi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=94aB3234479e0066bfb228b3a0e716ef57c0e660ef02dc0209c12b8f8fd394142b941
app.jwt.expiration-ms=86400000

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Google Gemini API
app.gemini.api-key=YOUR_GEMINI_API_KEY_HERE
